apiVersion: v1
kind: Service
metadata:
  name: wefox-challenge-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30000
  selector:
      app: wefox-challenge-pod
